In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('data_spain.csv')
data

,Unnamed: 0,habitants,minimun_salary,modal_salary,maximum_salary,average_salary,immigrants,unemployment_rate,violations_per_1000_inhabitants,number_of_violations,average_healthcare_satisfaction,average_annual_expenditure_household,average_annual_expenditure_person,rent_actual,index,poverty_risk_rate,inflation_rate,satisfaction_rate
0,andalucia,8472407,8185.05,18671.83,39781.75,"1.837,3",555831.0,18.68,27.24,230571,6.475000,26965.4,10479.9,681.0,8,32.3,10.5,7.0
1,aragon,1326261,8931.40,20604.72,40084.06,"1.972,4",110010.0,8.96,22.52,29944,6.879167,28627.3,12022.0,673.0,9,15.8,11.0,7.0
2,asturias,1011792,8418.88,21559.07,44353.81,"2.161,5",48058.0,11.36,18.66,19014,7.400000,26092.7,11855.9,648.0,10,20.4,10.3,7.0
3,balearic_islands,1173008,10941.15,20276.91,39540.39,"1.844,8",180360.0,9.29,39.57,46362,7.275000,31177.4,11954.8,914.0,11,17.6,9.7,7.0
4,basque_country,2213993,10754.04,26104.00,49426.00,"2.278,8",100701.0,8.75,27.41,60867,7.400000,33045.2,13981.6,1047.0,23,12.2,9.6,7.0
5,canary_islands,2172944,8793.55,17379.17,37890.54,"1.775,7",276827.0,17.76,27.38,59582,6.450000,25035.3,9689.6,766.0,12,28.4,8.5,7.0
6,cantabria,584507,9362.49,20114.15,41000.00,"1.941,0",30057.0,8.17,24.34,14185,7.175000,26673.0,11270.5,762.0,13,15.4,10.0,7.0
7,castilla_la_mancha,2049562,8380.32,18618.90,38397.28,"1.892,3",135761.0,14.11,24.15,49387,7.075000,24290.5,9587.5,480.0,15,27.4,12.7,7.0
8,castilla_y_leon,2383139,8772.96,19152.61,38081.30,"1.950,5",121761.0,10.19,22.37,53570,6.875000,27172.4,11930.6,589.0,14,17.9,11.6,7.0
9,catalonia,7763362,9541.39,22319.40,46227.08,"2.158,1",923156.0,9.29,36.30,282413,6.575000,31710.1,12856.5,1103.0,16,14.8,9.7,7.0
10,ceuta,83517,NaN,NaN,NaN,NaN,6474.0,22.75,34.65,5934,5.875000,30469.1,10190.5,NaN,25,32.3,9.3,7.0
11,extremadura,1059501,7452.20,17110.33,35324.71,"1.760,5",27870.0,16.73,18.54,19727,7.000000,24826.8,10304.3,444.0,18,32.3,10.6,7.0
12,galicia,2695645,8824.97,18813.49,38318.99,"1.941,9",152422.0,11.20,23.13,62490,6.975000,28429.6,11805.5,587.0,19,20.2,11.1,6.0
13,la_rioja,319796,8516.62,19944.00,39682.46,"1.947,3",34795.0,10.19,20.54,6527,7.300000,26605.4,11263.7,603.0,24,16.1,10.6,7.0
14,madrid,6751251,10063.68,22262.74,51938.58,"2.350,2",882293.0,10.18,36.75,249167,6.950000,34326.2,13541.0,1102.0,20,15.2,9.5,7.0
15,melilla,86261,NaN,NaN,NaN,NaN,13244.0,24.66,35.02,5997,6.050000,25174.0,8337.0,NaN,26,30.1,10.1,NaN
16,murcia,1518486,8938.21,18519.90,39487.41,"1.843,4",184463.0,12.18,27.86,42102,6.625000,27555.9,10159.2,594.0,21,27.7,10.9,7.0
17,navarra,661537,10070.98,24978.02,24978.02,"2.209,2",51107.0,8.76,29.12,19255,7.500000,32676.8,13150.5,804.0,22,9.8,10.2,7.0
18,valencian_community,5058138,7705.15,18650.01,39437.05,"1.920,7",691332.0,12.81,32.67,165233,6.850000,28057.3,11461.2,674.0,17,25.1,10.2,7.0

In [3]:
#OOPS!! THERE IS A COLUMN INDEX.. NEED TO DROP IT.
data = data.drop(columns=['index'])

In [4]:
data.dtypes

Unnamed: 0                               object
habitants                                 int64
minimun_salary                          float64
modal_salary                            float64
maximum_salary                          float64
average_salary                           object
immigrants                              float64
unemployment_rate                       float64
violations_per_1000_inhabitants         float64
number_of_violations                      int64
average_healthcare_satisfaction         float64
average_annual_expenditure_household    float64
average_annual_expenditure_person       float64
rent_actual                             float64
poverty_risk_rate                       float64
inflation_rate                          float64
satisfaction_rate                       float64
dtype: object

In [5]:
data['average_salary'] = data['average_salary'].astype(str)
data['average_salary'] = data['average_salary'].str.replace('.', '')

/var/folders/gj/4j_ddf3s73x6p0hjdxl3kfn80000gp/T/ipykernel_4162/4245546840.py:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  data['average_salary'] = data['average_salary'].str.replace('.', '')

In [6]:
data['average_salary'] = data['average_salary'].str.replace(',', '.')

In [7]:
data['average_salary'] = data['average_salary'].astype(float)

In [8]:
#to solve the nans of ceuta and melilla,I decided to drop ceuta and name use melilla to represent them both
#because both have almost the same value and they belong to the same autonomous community
#we could use the rule of 3 with andalucia. basing of the annual expenditure per household
#for the reason it is considered to have the same territorial scope which includes law and regulations.

In [9]:
data.index

RangeIndex(start=0, stop=19, step=1)

In [10]:
data = data.drop([10])

In [11]:
data = data.reset_index()

In [12]:
data=data.drop(['index'],axis=1)
data

,Unnamed: 0,habitants,minimun_salary,modal_salary,maximum_salary,average_salary,immigrants,unemployment_rate,violations_per_1000_inhabitants,number_of_violations,average_healthcare_satisfaction,average_annual_expenditure_household,average_annual_expenditure_person,rent_actual,poverty_risk_rate,inflation_rate,satisfaction_rate
0,andalucia,8472407,8185.05,18671.83,39781.75,1837.3,555831.0,18.68,27.24,230571,6.475000,26965.4,10479.9,681.0,32.3,10.5,7.0
1,aragon,1326261,8931.40,20604.72,40084.06,1972.4,110010.0,8.96,22.52,29944,6.879167,28627.3,12022.0,673.0,15.8,11.0,7.0
2,asturias,1011792,8418.88,21559.07,44353.81,2161.5,48058.0,11.36,18.66,19014,7.400000,26092.7,11855.9,648.0,20.4,10.3,7.0
3,balearic_islands,1173008,10941.15,20276.91,39540.39,1844.8,180360.0,9.29,39.57,46362,7.275000,31177.4,11954.8,914.0,17.6,9.7,7.0
4,basque_country,2213993,10754.04,26104.00,49426.00,2278.8,100701.0,8.75,27.41,60867,7.400000,33045.2,13981.6,1047.0,12.2,9.6,7.0
5,canary_islands,2172944,8793.55,17379.17,37890.54,1775.7,276827.0,17.76,27.38,59582,6.450000,25035.3,9689.6,766.0,28.4,8.5,7.0
6,cantabria,584507,9362.49,20114.15,41000.00,1941.0,30057.0,8.17,24.34,14185,7.175000,26673.0,11270.5,762.0,15.4,10.0,7.0
7,castilla_la_mancha,2049562,8380.32,18618.90,38397.28,1892.3,135761.0,14.11,24.15,49387,7.075000,24290.5,9587.5,480.0,27.4,12.7,7.0
8,castilla_y_leon,2383139,8772.96,19152.61,38081.30,1950.5,121761.0,10.19,22.37,53570,6.875000,27172.4,11930.6,589.0,17.9,11.6,7.0
9,catalonia,7763362,9541.39,22319.40,46227.08,2158.1,923156.0,9.29,36.30,282413,6.575000,31710.1,12856.5,1103.0,14.8,9.7,7.0
10,extremadura,1059501,7452.20,17110.33,35324.71,1760.5,27870.0,16.73,18.54,19727,7.000000,24826.8,10304.3,444.0,32.3,10.6,7.0
11,galicia,2695645,8824.97,18813.49,38318.99,1941.9,152422.0,11.20,23.13,62490,6.975000,28429.6,11805.5,587.0,20.2,11.1,6.0
12,la_rioja,319796,8516.62,19944.00,39682.46,1947.3,34795.0,10.19,20.54,6527,7.300000,26605.4,11263.7,603.0,16.1,10.6,7.0
13,madrid,6751251,10063.68,22262.74,51938.58,2350.2,882293.0,10.18,36.75,249167,6.950000,34326.2,13541.0,1102.0,15.2,9.5,7.0
14,melilla,86261,NaN,NaN,NaN,NaN,13244.0,24.66,35.02,5997,6.050000,25174.0,8337.0,NaN,30.1,10.1,NaN
15,murcia,1518486,8938.21,18519.90,39487.41,1843.4,184463.0,12.18,27.86,42102,6.625000,27555.9,10159.2,594.0,27.7,10.9,7.0
16,navarra,661537,10070.98,24978.02,24978.02,2209.2,51107.0,8.76,29.12,19255,7.500000,32676.8,13150.5,804.0,9.8,10.2,7.0
17,valencian_community,5058138,7705.15,18650.01,39437.05,1920.7,691332.0,12.81,32.67,165233,6.850000,28057.3,11461.2,674.0,25.1,10.2,7.0

In [13]:
data = data.set_index('Unnamed: 0')

In [14]:
data = data.rename(index={'melilla':'ceuta y melilla'})

##### in the next step, I decide which type of salary to test , minimum, modal, maximum or average -- I decided to take the modal salary per year, which is what most of the people earn.

In [15]:
data = data.drop(columns=['minimun_salary', 'maximum_salary', 'average_salary'])

#### DEALING WITH NaNs

In [16]:
data['modal_salary']= data['modal_salary'].fillna((18671.83*25174.0)/26965.4)
#rule of 3 with the values of modal salary and avg anual expenditures of andalucia

In [17]:
data['rent_actual']= data['rent_actual'].fillna((25174*681.0)/26965.4)
#rule of 3 with the values of avg anual expenditures and houserent of andalucia

In [18]:
#lets's put the mode of the satisfaction rate, for the reason that they all have the same values.
# data['satisfaction_rate'].fillna(data['satisfaction_rate'].mode()) #returns me the whole column with 'None'
data

,habitants,modal_salary,immigrants,unemployment_rate,violations_per_1000_inhabitants,number_of_violations,average_healthcare_satisfaction,average_annual_expenditure_household,average_annual_expenditure_person,rent_actual,poverty_risk_rate,inflation_rate,satisfaction_rate
Unnamed: 0,,,,,,,,,,,,,
andalucia,8472407,18671.830000,555831.0,18.68,27.24,230571,6.475000,26965.4,10479.9,681.000000,32.3,10.5,7.0
aragon,1326261,20604.720000,110010.0,8.96,22.52,29944,6.879167,28627.3,12022.0,673.000000,15.8,11.0,7.0
asturias,1011792,21559.070000,48058.0,11.36,18.66,19014,7.400000,26092.7,11855.9,648.000000,20.4,10.3,7.0
balearic_islands,1173008,20276.910000,180360.0,9.29,39.57,46362,7.275000,31177.4,11954.8,914.000000,17.6,9.7,7.0
basque_country,2213993,26104.000000,100701.0,8.75,27.41,60867,7.400000,33045.2,13981.6,1047.000000,12.2,9.6,7.0
canary_islands,2172944,17379.170000,276827.0,17.76,27.38,59582,6.450000,25035.3,9689.6,766.000000,28.4,8.5,7.0
cantabria,584507,20114.150000,30057.0,8.17,24.34,14185,7.175000,26673.0,11270.5,762.000000,15.4,10.0,7.0
castilla_la_mancha,2049562,18618.900000,135761.0,14.11,24.15,49387,7.075000,24290.5,9587.5,480.000000,27.4,12.7,7.0
castilla_y_leon,2383139,19152.610000,121761.0,10.19,22.37,53570,6.875000,27172.4,11930.6,589.000000,17.9,11.6,7.0
catalonia,7763362,22319.400000,923156.0,9.29,36.30,282413,6.575000,31710.1,12856.5,1103.000000,14.8,9.7,7.0
extremadura,1059501,17110.330000,27870.0,16.73,18.54,19727,7.000000,24826.8,10304.3,444.000000,32.3,10.6,7.0
galicia,2695645,18813.490000,152422.0,11.20,23.13,62490,6.975000,28429.6,11805.5,587.000000,20.2,11.1,6.0
la_rioja,319796,19944.000000,34795.0,10.19,20.54,6527,7.300000,26605.4,11263.7,603.000000,16.1,10.6,7.0
madrid,6751251,22262.740000,882293.0,10.18,36.75,249167,6.950000,34326.2,13541.0,1102.000000,15.2,9.5,7.0
ceuta y melilla,86261,17431.399068,13244.0,24.66,35.02,5997,6.050000,25174.0,8337.0,635.758936,30.1,10.1,NaN
murcia,1518486,18519.900000,184463.0,12.18,27.86,42102,6.625000,27555.9,10159.2,594.000000,27.7,10.9,7.0
navarra,661537,24978.020000,51107.0,8.76,29.12,19255,7.500000,32676.8,13150.5,804.000000,9.8,10.2,7.0
valencian_community,5058138,18650.010000,691332.0,12.81,32.67,165233,6.850000,28057.3,11461.2,674.000000,25.1,10.2,7.0

In [19]:
data['satisfaction_rate'].isna()

Unnamed: 0
andalucia              False
aragon                 False
asturias               False
balearic_islands       False
basque_country         False
canary_islands         False
cantabria              False
castilla_la_mancha     False
castilla_y_leon        False
catalonia              False
extremadura            False
galicia                False
la_rioja               False
madrid                 False
ceuta y melilla         True
murcia                 False
navarra                False
valencian_community    False
Name: satisfaction_rate, dtype: bool

In [20]:
data['satisfaction_rate'] = data['satisfaction_rate'].fillna(data['satisfaction_rate'].mean())

In [21]:
# num = data['satisfaction_rate'].mode()
# data['satisfaction_rate'].fillna(num, inplace=True)

In [22]:
data

,habitants,modal_salary,immigrants,unemployment_rate,violations_per_1000_inhabitants,number_of_violations,average_healthcare_satisfaction,average_annual_expenditure_household,average_annual_expenditure_person,rent_actual,poverty_risk_rate,inflation_rate,satisfaction_rate
Unnamed: 0,,,,,,,,,,,,,
andalucia,8472407,18671.830000,555831.0,18.68,27.24,230571,6.475000,26965.4,10479.9,681.000000,32.3,10.5,7.000000
aragon,1326261,20604.720000,110010.0,8.96,22.52,29944,6.879167,28627.3,12022.0,673.000000,15.8,11.0,7.000000
asturias,1011792,21559.070000,48058.0,11.36,18.66,19014,7.400000,26092.7,11855.9,648.000000,20.4,10.3,7.000000
balearic_islands,1173008,20276.910000,180360.0,9.29,39.57,46362,7.275000,31177.4,11954.8,914.000000,17.6,9.7,7.000000
basque_country,2213993,26104.000000,100701.0,8.75,27.41,60867,7.400000,33045.2,13981.6,1047.000000,12.2,9.6,7.000000
canary_islands,2172944,17379.170000,276827.0,17.76,27.38,59582,6.450000,25035.3,9689.6,766.000000,28.4,8.5,7.000000
cantabria,584507,20114.150000,30057.0,8.17,24.34,14185,7.175000,26673.0,11270.5,762.000000,15.4,10.0,7.000000
castilla_la_mancha,2049562,18618.900000,135761.0,14.11,24.15,49387,7.075000,24290.5,9587.5,480.000000,27.4,12.7,7.000000
castilla_y_leon,2383139,19152.610000,121761.0,10.19,22.37,53570,6.875000,27172.4,11930.6,589.000000,17.9,11.6,7.000000
catalonia,7763362,22319.400000,923156.0,9.29,36.30,282413,6.575000,31710.1,12856.5,1103.000000,14.8,9.7,7.000000
extremadura,1059501,17110.330000,27870.0,16.73,18.54,19727,7.000000,24826.8,10304.3,444.000000,32.3,10.6,7.000000
galicia,2695645,18813.490000,152422.0,11.20,23.13,62490,6.975000,28429.6,11805.5,587.000000,20.2,11.1,6.000000
la_rioja,319796,19944.000000,34795.0,10.19,20.54,6527,7.300000,26605.4,11263.7,603.000000,16.1,10.6,7.000000
madrid,6751251,22262.740000,882293.0,10.18,36.75,249167,6.950000,34326.2,13541.0,1102.000000,15.2,9.5,7.000000
ceuta y melilla,86261,17431.399068,13244.0,24.66,35.02,5997,6.050000,25174.0,8337.0,635.758936,30.1,10.1,6.941176
murcia,1518486,18519.900000,184463.0,12.18,27.86,42102,6.625000,27555.9,10159.2,594.000000,27.7,10.9,7.000000
navarra,661537,24978.020000,51107.0,8.76,29.12,19255,7.500000,32676.8,13150.5,804.000000,9.8,10.2,7.000000
valencian_community,5058138,18650.010000,691332.0,12.81,32.67,165233,6.850000,28057.3,11461.2,674.000000,25.1,10.2,7.000000

In [23]:
#now i will do the percentage of immigrants per habitants to be able to drop the 'immigrant' column
data['percentage_immigrats'] = (data['immigrants'] * 100)/data['habitants']

In [24]:
# data = data.drop(columns=['immigrants'])

In [25]:
#I realized that I needed to also drop the 'number_of_violations' column because I already have the percentage.
#I would also drop the 'average_annual_expenditure_household' because I just wanted to work with the individual expenditure.
data = data.drop(columns=['average_annual_expenditure_household', 'number_of_violations'])
data

,habitants,modal_salary,immigrants,unemployment_rate,violations_per_1000_inhabitants,average_healthcare_satisfaction,average_annual_expenditure_person,rent_actual,poverty_risk_rate,inflation_rate,satisfaction_rate,percentage_immigrats
Unnamed: 0,,,,,,,,,,,,
andalucia,8472407,18671.830000,555831.0,18.68,27.24,6.475000,10479.9,681.000000,32.3,10.5,7.000000,6.560485
aragon,1326261,20604.720000,110010.0,8.96,22.52,6.879167,12022.0,673.000000,15.8,11.0,7.000000,8.294747
asturias,1011792,21559.070000,48058.0,11.36,18.66,7.400000,11855.9,648.000000,20.4,10.3,7.000000,4.749790
balearic_islands,1173008,20276.910000,180360.0,9.29,39.57,7.275000,11954.8,914.000000,17.6,9.7,7.000000,15.375854
basque_country,2213993,26104.000000,100701.0,8.75,27.41,7.400000,13981.6,1047.000000,12.2,9.6,7.000000,4.548388
canary_islands,2172944,17379.170000,276827.0,17.76,27.38,6.450000,9689.6,766.000000,28.4,8.5,7.000000,12.739721
cantabria,584507,20114.150000,30057.0,8.17,24.34,7.175000,11270.5,762.000000,15.4,10.0,7.000000,5.142282
castilla_la_mancha,2049562,18618.900000,135761.0,14.11,24.15,7.075000,9587.5,480.000000,27.4,12.7,7.000000,6.623903
castilla_y_leon,2383139,19152.610000,121761.0,10.19,22.37,6.875000,11930.6,589.000000,17.9,11.6,7.000000,5.109270
catalonia,7763362,22319.400000,923156.0,9.29,36.30,6.575000,12856.5,1103.000000,14.8,9.7,7.000000,11.891188
extremadura,1059501,17110.330000,27870.0,16.73,18.54,7.000000,10304.3,444.000000,32.3,10.6,7.000000,2.630484
galicia,2695645,18813.490000,152422.0,11.20,23.13,6.975000,11805.5,587.000000,20.2,11.1,6.000000,5.654380
la_rioja,319796,19944.000000,34795.0,10.19,20.54,7.300000,11263.7,603.000000,16.1,10.6,7.000000,10.880374
madrid,6751251,22262.740000,882293.0,10.18,36.75,6.950000,13541.0,1102.000000,15.2,9.5,7.000000,13.068585
ceuta y melilla,86261,17431.399068,13244.0,24.66,35.02,6.050000,8337.0,635.758936,30.1,10.1,6.941176,15.353404
murcia,1518486,18519.900000,184463.0,12.18,27.86,6.625000,10159.2,594.000000,27.7,10.9,7.000000,12.147824
navarra,661537,24978.020000,51107.0,8.76,29.12,7.500000,13150.5,804.000000,9.8,10.2,7.000000,7.725494
valencian_community,5058138,18650.010000,691332.0,12.81,32.67,6.850000,11461.2,674.000000,25.1,10.2,7.000000,13.667717

In [26]:
#NOW, I HAD TO SEE THE PERCENTAGE OF THE EXPENSES BY WORKING ON THE 'modal_salary', 'average_annual_expenditure_person' and 'rent_actual' columns

#I needed to multiply 'rent_actual' by 12 so I will know how much does the annual rent costs.

data['annual_rent'] = data['rent_actual'] * 12
data

,habitants,modal_salary,immigrants,unemployment_rate,violations_per_1000_inhabitants,average_healthcare_satisfaction,average_annual_expenditure_person,rent_actual,poverty_risk_rate,inflation_rate,satisfaction_rate,percentage_immigrats,annual_rent
Unnamed: 0,,,,,,,,,,,,,
andalucia,8472407,18671.830000,555831.0,18.68,27.24,6.475000,10479.9,681.000000,32.3,10.5,7.000000,6.560485,8172.000000
aragon,1326261,20604.720000,110010.0,8.96,22.52,6.879167,12022.0,673.000000,15.8,11.0,7.000000,8.294747,8076.000000
asturias,1011792,21559.070000,48058.0,11.36,18.66,7.400000,11855.9,648.000000,20.4,10.3,7.000000,4.749790,7776.000000
balearic_islands,1173008,20276.910000,180360.0,9.29,39.57,7.275000,11954.8,914.000000,17.6,9.7,7.000000,15.375854,10968.000000
basque_country,2213993,26104.000000,100701.0,8.75,27.41,7.400000,13981.6,1047.000000,12.2,9.6,7.000000,4.548388,12564.000000
canary_islands,2172944,17379.170000,276827.0,17.76,27.38,6.450000,9689.6,766.000000,28.4,8.5,7.000000,12.739721,9192.000000
cantabria,584507,20114.150000,30057.0,8.17,24.34,7.175000,11270.5,762.000000,15.4,10.0,7.000000,5.142282,9144.000000
castilla_la_mancha,2049562,18618.900000,135761.0,14.11,24.15,7.075000,9587.5,480.000000,27.4,12.7,7.000000,6.623903,5760.000000
castilla_y_leon,2383139,19152.610000,121761.0,10.19,22.37,6.875000,11930.6,589.000000,17.9,11.6,7.000000,5.109270,7068.000000
catalonia,7763362,22319.400000,923156.0,9.29,36.30,6.575000,12856.5,1103.000000,14.8,9.7,7.000000,11.891188,13236.000000
extremadura,1059501,17110.330000,27870.0,16.73,18.54,7.000000,10304.3,444.000000,32.3,10.6,7.000000,2.630484,5328.000000
galicia,2695645,18813.490000,152422.0,11.20,23.13,6.975000,11805.5,587.000000,20.2,11.1,6.000000,5.654380,7044.000000
la_rioja,319796,19944.000000,34795.0,10.19,20.54,7.300000,11263.7,603.000000,16.1,10.6,7.000000,10.880374,7236.000000
madrid,6751251,22262.740000,882293.0,10.18,36.75,6.950000,13541.0,1102.000000,15.2,9.5,7.000000,13.068585,13224.000000
ceuta y melilla,86261,17431.399068,13244.0,24.66,35.02,6.050000,8337.0,635.758936,30.1,10.1,6.941176,15.353404,7629.107226
murcia,1518486,18519.900000,184463.0,12.18,27.86,6.625000,10159.2,594.000000,27.7,10.9,7.000000,12.147824,7128.000000
navarra,661537,24978.020000,51107.0,8.76,29.12,7.500000,13150.5,804.000000,9.8,10.2,7.000000,7.725494,9648.000000
valencian_community,5058138,18650.010000,691332.0,12.81,32.67,6.850000,11461.2,674.000000,25.1,10.2,7.000000,13.667717,8088.000000

##### now, i will add a column called annual_expenses in which I will sum the column average_anual_expenditure_person with annual_rent

In [27]:
data['annual_expenses'] = data['average_annual_expenditure_person'] + data['annual_rent']
data

,habitants,modal_salary,immigrants,unemployment_rate,violations_per_1000_inhabitants,average_healthcare_satisfaction,average_annual_expenditure_person,rent_actual,poverty_risk_rate,inflation_rate,satisfaction_rate,percentage_immigrats,annual_rent,annual_expenses
Unnamed: 0,,,,,,,,,,,,,,
andalucia,8472407,18671.830000,555831.0,18.68,27.24,6.475000,10479.9,681.000000,32.3,10.5,7.000000,6.560485,8172.000000,18651.900000
aragon,1326261,20604.720000,110010.0,8.96,22.52,6.879167,12022.0,673.000000,15.8,11.0,7.000000,8.294747,8076.000000,20098.000000
asturias,1011792,21559.070000,48058.0,11.36,18.66,7.400000,11855.9,648.000000,20.4,10.3,7.000000,4.749790,7776.000000,19631.900000
balearic_islands,1173008,20276.910000,180360.0,9.29,39.57,7.275000,11954.8,914.000000,17.6,9.7,7.000000,15.375854,10968.000000,22922.800000
basque_country,2213993,26104.000000,100701.0,8.75,27.41,7.400000,13981.6,1047.000000,12.2,9.6,7.000000,4.548388,12564.000000,26545.600000
canary_islands,2172944,17379.170000,276827.0,17.76,27.38,6.450000,9689.6,766.000000,28.4,8.5,7.000000,12.739721,9192.000000,18881.600000
cantabria,584507,20114.150000,30057.0,8.17,24.34,7.175000,11270.5,762.000000,15.4,10.0,7.000000,5.142282,9144.000000,20414.500000
castilla_la_mancha,2049562,18618.900000,135761.0,14.11,24.15,7.075000,9587.5,480.000000,27.4,12.7,7.000000,6.623903,5760.000000,15347.500000
castilla_y_leon,2383139,19152.610000,121761.0,10.19,22.37,6.875000,11930.6,589.000000,17.9,11.6,7.000000,5.109270,7068.000000,18998.600000
catalonia,7763362,22319.400000,923156.0,9.29,36.30,6.575000,12856.5,1103.000000,14.8,9.7,7.000000,11.891188,13236.000000,26092.500000
extremadura,1059501,17110.330000,27870.0,16.73,18.54,7.000000,10304.3,444.000000,32.3,10.6,7.000000,2.630484,5328.000000,15632.300000
galicia,2695645,18813.490000,152422.0,11.20,23.13,6.975000,11805.5,587.000000,20.2,11.1,6.000000,5.654380,7044.000000,18849.500000
la_rioja,319796,19944.000000,34795.0,10.19,20.54,7.300000,11263.7,603.000000,16.1,10.6,7.000000,10.880374,7236.000000,18499.700000
madrid,6751251,22262.740000,882293.0,10.18,36.75,6.950000,13541.0,1102.000000,15.2,9.5,7.000000,13.068585,13224.000000,26765.000000
ceuta y melilla,86261,17431.399068,13244.0,24.66,35.02,6.050000,8337.0,635.758936,30.1,10.1,6.941176,15.353404,7629.107226,15966.107226
murcia,1518486,18519.900000,184463.0,12.18,27.86,6.625000,10159.2,594.000000,27.7,10.9,7.000000,12.147824,7128.000000,17287.200000
navarra,661537,24978.020000,51107.0,8.76,29.12,7.500000,13150.5,804.000000,9.8,10.2,7.000000,7.725494,9648.000000,22798.500000
valencian_community,5058138,18650.010000,691332.0,12.81,32.67,6.850000,11461.2,674.000000,25.1,10.2,7.000000,13.667717,8088.000000,19549.200000

##### I'll add another column called 'savings' subracting the annual_expenses with modal_salary column

In [28]:
data['savings'] = data['modal_salary'] - data['annual_expenses']

In [29]:
data = np.round(data, decimals=2)

#### salary-expense balance

In [30]:
data.savings.nlargest(3)
#top 3 autonomous region with great salary-expense balance

Unnamed: 0
castilla_la_mancha    3271.40
navarra               2179.52
asturias              1927.17
Name: savings, dtype: float64

In [31]:
data.savings.nsmallest(3)
#top 3 autonomous region with worse salary-expense balance

Unnamed: 0
madrid             -4502.26
catalonia          -3773.10
balearic_islands   -2645.89
Name: savings, dtype: float64

#### unemployment best&worst

In [32]:
data.unemployment_rate.nlargest(3)

Unnamed: 0
ceuta y melilla    24.66
andalucia          18.68
canary_islands     17.76
Name: unemployment_rate, dtype: float64

In [33]:
data.unemployment_rate.nsmallest(3)

Unnamed: 0
cantabria         8.17
basque_country    8.75
navarra           8.76
Name: unemployment_rate, dtype: float64

#### top 3 safest& most unsafe

In [34]:
data.violations_per_1000_inhabitants.nlargest(3)

Unnamed: 0
balearic_islands    39.57
madrid              36.75
catalonia           36.30
Name: violations_per_1000_inhabitants, dtype: float64

In [35]:
data.violations_per_1000_inhabitants.nsmallest(3)

Unnamed: 0
extremadura    18.54
asturias       18.66
la_rioja       20.54
Name: violations_per_1000_inhabitants, dtype: float64

#### best-worst healthcare system

In [36]:
data.average_healthcare_satisfaction.nlargest(1)

Unnamed: 0
navarra    7.5
Name: average_healthcare_satisfaction, dtype: float64

In [37]:
data.average_healthcare_satisfaction.nsmallest(1)

Unnamed: 0
ceuta y melilla    6.05
Name: average_healthcare_satisfaction, dtype: float64

In [38]:
data.to_csv('data_spain2')

## Making a copy of Cleaned data

In [39]:
data2 = data.copy()

In [40]:
data2.columns

Index(['habitants', 'modal_salary', 'immigrants', 'unemployment_rate',
       'violations_per_1000_inhabitants', 'average_healthcare_satisfaction',
       'average_annual_expenditure_person', 'rent_actual', 'poverty_risk_rate',
       'inflation_rate', 'satisfaction_rate', 'percentage_immigrats',
       'annual_rent', 'annual_expenses', 'savings'],
      dtype='object')

In [41]:
data2.columns = data2.columns.str.replace('_',' ')

In [42]:
data2.columns = data2.columns.str.capitalize()

In [43]:
data2.index = data2.index.rename('Autonomous Community')

In [44]:
data2.index = data2.index.str.replace('_',' ')

In [45]:
data2.index = data2.index.str.title()

In [46]:
data2

,Habitants,Modal salary,Immigrants,Unemployment rate,Violations per 1000 inhabitants,Average healthcare satisfaction,Average annual expenditure person,Rent actual,Poverty risk rate,Inflation rate,Satisfaction rate,Percentage immigrats,Annual rent,Annual expenses,Savings
Autonomous Community,,,,,,,,,,,,,,,
Andalucia,8472407,18671.83,555831.0,18.68,27.24,6.48,10479.9,681.00,32.3,10.5,7.00,6.56,8172.00,18651.90,19.93
Aragon,1326261,20604.72,110010.0,8.96,22.52,6.88,12022.0,673.00,15.8,11.0,7.00,8.29,8076.00,20098.00,506.72
Asturias,1011792,21559.07,48058.0,11.36,18.66,7.40,11855.9,648.00,20.4,10.3,7.00,4.75,7776.00,19631.90,1927.17
Balearic Islands,1173008,20276.91,180360.0,9.29,39.57,7.28,11954.8,914.00,17.6,9.7,7.00,15.38,10968.00,22922.80,-2645.89
Basque Country,2213993,26104.00,100701.0,8.75,27.41,7.40,13981.6,1047.00,12.2,9.6,7.00,4.55,12564.00,26545.60,-441.60
Canary Islands,2172944,17379.17,276827.0,17.76,27.38,6.45,9689.6,766.00,28.4,8.5,7.00,12.74,9192.00,18881.60,-1502.43
Cantabria,584507,20114.15,30057.0,8.17,24.34,7.18,11270.5,762.00,15.4,10.0,7.00,5.14,9144.00,20414.50,-300.35
Castilla La Mancha,2049562,18618.90,135761.0,14.11,24.15,7.07,9587.5,480.00,27.4,12.7,7.00,6.62,5760.00,15347.50,3271.40
Castilla Y Leon,2383139,19152.61,121761.0,10.19,22.37,6.88,11930.6,589.00,17.9,11.6,7.00,5.11,7068.00,18998.60,154.01
Catalonia,7763362,22319.40,923156.0,9.29,36.30,6.58,12856.5,1103.00,14.8,9.7,7.00,11.89,13236.00,26092.50,-3773.10
Extremadura,1059501,17110.33,27870.0,16.73,18.54,7.00,10304.3,444.00,32.3,10.6,7.00,2.63,5328.00,15632.30,1478.03
Galicia,2695645,18813.49,152422.0,11.20,23.13,6.98,11805.5,587.00,20.2,11.1,6.00,5.65,7044.00,18849.50,-36.01
La Rioja,319796,19944.00,34795.0,10.19,20.54,7.30,11263.7,603.00,16.1,10.6,7.00,10.88,7236.00,18499.70,1444.30
Madrid,6751251,22262.74,882293.0,10.18,36.75,6.95,13541.0,1102.00,15.2,9.5,7.00,13.07,13224.00,26765.00,-4502.26
Ceuta Y Melilla,86261,17431.40,13244.0,24.66,35.02,6.05,8337.0,635.76,30.1,10.1,6.94,15.35,7629.11,15966.11,1465.29
Murcia,1518486,18519.90,184463.0,12.18,27.86,6.62,10159.2,594.00,27.7,10.9,7.00,12.15,7128.00,17287.20,1232.70
Navarra,661537,24978.02,51107.0,8.76,29.12,7.50,13150.5,804.00,9.8,10.2,7.00,7.73,9648.00,22798.50,2179.52
Valencian Community,5058138,18650.01,691332.0,12.81,32.67,6.85,11461.2,674.00,25.1,10.2,7.00,13.67,8088.00,19549.20,-899.19

In [47]:
#Tableau won't accept the names of some autonomous community, so we need to change them
data2 = data2.rename(index={'Balearic_Islands': 'Islas Baleares', })

In [48]:
data2.to_csv('/Users/user/Downloads/final_table.csv')

In [49]:
data2.to_excel('/Users/user/Downloads/final_table.xlsx')

# Hypothesis testing

##### In this section of the lab, we will test whether the monthly savings or the extra money that people have at the end of the year is significantly different from 3271.40€ that people in Navarra save.

In [50]:
import scipy.stats as st
from scipy.stats import ttest_1samp

In [51]:
savings = data['savings'].dropna()

In [52]:
#Two-sided test:
    # Null hypothesis or H0: savings = 3271.40€/year
    # Alternative hyp or H1: savings != 3271.40€/year

stat, pval = ttest_1samp(savings, 3271.40)

print('stat is  ', stat)
print('pvalue for the two-tailed test is  ', pval)
print('pvalue for the one-tailed test is  ', pval/2)

stat is   -6.7814449033403905
pvalue for the two-tailed test is   3.203706433525419e-06
pvalue for the one-tailed test is   1.6018532167627095e-06

##### based on the hypothesis, we reject the null hypothesis

In [53]:
data.describe().T
#here, it is shown that the mean saving of people who live in spain doesn't even reach a euro if you even if you try to live with your minimal needs. (shelter,food,clothing)

,count,mean,std,min,25%,50%,75%,max
habitants,18.0,2.627866e+06,2.591381e+06,86261.00,1.023719e+06,1784024.000,2.617518e+06,8472407.00
modal_salary,18.0,2.013948e+04,2.505351e+03,17110.33,1.862668e+04,19548.305,2.132048e+04,26104.00
immigrants,18.0,2.511138e+05,2.982704e+05,13244.00,4.882025e+04,128761.000,2.537360e+05,923156.00
unemployment_rate,18.0,1.240389e+01,4.427360e+00,8.17,9.290000e+00,10.695,1.378500e+01,24.66
violations_per_1000_inhabitants,18.0,2.742056e+01,6.384670e+00,18.54,2.267250e+01,27.310,3.178250e+01,39.57
average_healthcare_satisfaction,18.0,6.936111e+00,3.874978e-01,6.05,6.677500e+00,6.965,7.255000e+00,7.50
average_annual_expenditure_person,18.0,1.142507e+04,1.475083e+03,8337.00,1.034820e+04,11633.350,1.200520e+04,13981.60
rent_actual,18.0,7.281533e+02,1.975191e+02,444.00,5.962500e+02,673.500,7.945000e+02,1103.00
poverty_risk_rate,18.0,2.103889e+01,7.174804e+00,9.80,1.550000e+01,19.050,2.762500e+01,32.30
inflation_rate,18.0,1.037778e+01,9.168716e-01,8.50,9.775000e+00,10.250,1.082500e+01,12.70
satisfaction_rate,18.0,6.941111e+00,2.352943e-01,6.00,7.000000e+00,7.000,7.000000e+00,7.00
percentage_immigrats,18.0,9.008889e+00,4.120444e+00,2.63,5.267500e+00,8.010,1.259250e+01,15.38
annual_rent,18.0,8.737839e+03,2.370230e+03,5328.00,7.155000e+03,8082.000,9.534000e+03,13236.00
annual_expenses,18.0,2.016291e+04,3.549193e+03,15347.50,1.853775e+04,19273.900,2.220250e+04,26765.00
savings,18.0,-2.343111e+01,2.061328e+03,-4502.26,-7.847925e+02,86.970,1.460043e+03,3271.40

In [54]:
data['inflation_rate'].mean()

10.377777777777775